# Dependencies
plugins: [jekyll-paginate, jekyll-scholar]
markdown            : kramdown
highlighter         : rouge

# Permalinks
permalink           : pretty
relative_permalinks : false

# Setup
title       : Manas George
tagline     : ''
description : 'Hacker, Programmer, Math geek.'
url         : www.mnsgrg.com
baseurl         :

author:
name                : 'Manas George'
url                 : www.mnsgrg.com

paginate            : 5
paginate_path       : "blog/page:num"

scholar:
    style: apa
    source: ./_bibliography
    bibliography: "**/*.bib"


# Custom vars
# version           : 1.0.0
# github            : https://github.com/ManasGeorge
# repo              : https://github.com/ManasGeorge/Website.git
